### PR TITLE
Global refactoring of the solution.

### PR DESCRIPTION
**Pull request by gukoff**
## Description

- Avoid double enumeration by using IList
- remove unused variables
- consistent field naming for provate/public fields
- var where possible
- typos

## Motivation and Context

Make code cleaner. Avoid double enumeration of IEnumberable-s.

## How Has This Been Tested?

Not tested yet

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
Hey @gukoff !

Can you find a bit of time to wrap up this so it can be merged? 😉 

Thanks!

**Comment by gukoff** [comment]
@josesimoes 
Hey! As I see you already went ahead and merged it yourself? :)

**Comment by josesimoes** [comment]
Build is failing...

**Comment by gukoff** [comment]
I see. Build was failing because of an old build SDK: `.net core 3.1` instead of `.net 5.0`.

Check our the last commit, if fixes the build. 

I'm not sure if updating the build SDK can be a breaking change for the end users of the tool. 
But I think it can't, because on the project level we still have `<TargetFrameworks>netcoreapp3.1;net472</TargetFrameworks>`.

**Comment by josesimoes** [comment]
> I see. Build was failing because of an old build SDK: `.net core 3.1` instead of `.net 5.0`.
> 
> Check our the last commit, if fixes the build.
> 
> I'm not sure if updating the build SDK can be a breaking change for the end users of the tool.
> But I think it can't, because on the project level we still have `<TargetFrameworks>netcoreapp3.1;net472</TargetFrameworks>`.

I believe it's doable. Let's give it a try and see if there are complains about it 😉

**Comment by gukoff** [comment]
Then all what's left to do is to review / merge :)

**Pull request merged**
