### PR TITLE
Update STLink

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Update to v2.15.0.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
@Ellerbach can you please take care of downloading the ZIPs for *nix and MAC and copy&paste to the respective folders?

**Comment by josesimoes** [comment]
@Ellerbach can you please look into this?

**Comment by Ellerbach** [comment]
> @Ellerbach can you please look into this?

So, it's not obvious, the installation fails on Linux (there are threads on this on STM32), I would rather keep the existing and proven to work STM versions for Mac and Linux, the time STM fixes the issues on those platforms (it's reported that the nex version do not work on M1/M2)

**Comment by josesimoes** [comment]
Sure thing! It's not broken or anything. just wanted to keep it up to date, but ST doesn't make it easy at all....

**Pull request closed without merging**
