### PR TITLE
Improve output during backup/flash process

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
Improve output during backup/flash process.

## Motivation and Context
- It feels like the flashing process is taking much more time recently so this change allows the user to be confident that work is progressing (see: https://github.com/nanoframework/Home/discussions/1510)

## How Has This Been Tested?
Manually

## Types of changes

- [X] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [X] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by torbacz** [comment]
After Jose comment, I thought about the same. Great work!

**Comment by torbacz** [comment]
Not quite sure if it should be different than nomal. Normal user uses command in "normal mode" and should be aware that "something" is going on.

**Comment by josesimoes** [comment]
@torbacz you've lost me there... 🤪 

My point is that I'm OK with showing the progress with normal verbosity (default). Not showing it when verbose is silent. 
So, I suppose we are in agreement...

**Comment by CoryCharlton** [comment]
> @CoryCharlton bring back those open/close statements, just change the verbosity condition to less than normal and OK to have the new one about the backup operation.

Hi @josesimoes , I'm not clear on what "open/close statements" you are referring to.

**Comment by josesimoes** [comment]
> Hi @josesimoes , I'm not clear on what "open/close statements" you are referring to.

Probably not the best word choice in English... 😅 I'm referring to the output statements that "open" and "close" the operations, like

`Console.Write($"Flashing firmware...");` <---- open 

`Console.WriteLine("OK");`  <--- close

I was asking to have those back, just changing the condition to output them to verbosity less than normal, so the feedback of the operation still shows on those conditions.

**Comment by CoryCharlton** [comment]
> > Hi @josesimoes , I'm not clear on what "open/close statements" you are referring to.
> 
> Probably not the best word choice in English... 😅 I'm referring to the output statements that "open" and "close" the operations, like
> 
> `Console.Write($"Flashing firmware...");` <---- open
> 
> `Console.WriteLine("OK");` <--- close
> 
> I was asking to have those back, just changing the condition to output them to verbosity less than normal, so the feedback of the operation still shows on those conditions.

Understood. 

That being said these weren't changed. The "Flashing firmware..." was moved from [here](https://github.com/nanoframework/nanoFirmwareFlasher/pull/281/files#diff-0105837069c3b0ce14c09864cabb5e65b9d0174870e5ef5042cad7b397a42ba4L498) to [here](https://github.com/nanoframework/nanoFirmwareFlasher/pull/281/files#diff-0105837069c3b0ce14c09864cabb5e65b9d0174870e5ef5042cad7b397a42ba4R543) so the "Backup configuration..." message could occur first.

The existing `BackupConfigPartition` [ignored failure](https://github.com/nanoframework/nanoFirmwareFlasher/blob/dd7153a3d8aa8c7f861522c54abdfb5dd0f661a8/nanoFirmwareFlasher.Library/Esp32Operations.cs#L533) so I did not add an "OK" message but that can be changed if we want.

**Comment by josesimoes** [comment]
@CoryCharlton I've just made some tweaks on this. Hope you're OK.
Despite ignoring the outcome of the backup operation we should keep a consistent look, otherwise can be confusing.

I've also adjusted the flashing output to be more consistent with the usual flow and have the full message there after the output of esptool. This will prevent breaking changes with any tools parsing the output.

If you're OK with all this, let's have this PR merged!

**Comment by CoryCharlton** [comment]
@josesimoes I further checked and refined the output. This is ready to be merged. 

Here's the output of the tests I ran:

nanoff.exe --platform esp32 --serialport COM11 --update

```
.NET nanoFramework Firmware Flasher v2.5.88+4e6c5c3387
Copyright (C) 2019 .NET Foundation and nanoFramework project contributors

** There is a new version available, update is recommended **
** You should consider updating via the 'dotnet tool update -g nanoff' command **
** If you have it installed on a specific path please check the instructions here: https://git.io/JiU0C **

Reading details from chip...OK                                                                                                            

Connected to:
ESP32-S3 (ESP32-S3 (QFN56) (revision v0.1))
Features WiFi, BLE
Flash size 16MB W25Q128_V from WINBOND_NEX (manufacturer 0x239 device 0x16408)
PSRAM: undetermined
Crystal 40MHz
MAC F4:12:FA:42:03:2C


No target name was provided! Using 'ESP32_S3' based on the device characteristics.

Extracting ESP32_S3-1.9.1.224.zip...OK

Updating to 1.9.1.224

Backup configuration...OK                                                                                                            
Flashing firmware...OK                                                                                                            

Process finished with exit code 0.
```

nanoff.exe --platform esp32 --serialport COM11 --update --masserase

```
.NET nanoFramework Firmware Flasher v2.5.88+4e6c5c3387
Copyright (C) 2019 .NET Foundation and nanoFramework project contributors

** There is a new version available, update is recommended **
** You should consider updating via the 'dotnet tool update -g nanoff' command **
** If you have it installed on a specific path please check the instructions here: https://git.io/JiU0C **

Reading details from chip...OK                                                                                                            

Connected to:
ESP32-S3 (ESP32-S3 (QFN56) (revision v0.1))
Features WiFi, BLE
Flash size 16MB W25Q128_V from WINBOND_NEX (manufacturer 0x239 device 0x16408)
PSRAM: undetermined
Crystal 40MHz
MAC F4:12:FA:42:03:2C


No target name was provided! Using 'ESP32_S3' based on the device characteristics.

Extracting ESP32_S3-1.9.1.224.zip...OK

Updating to 1.9.1.224

Erasing flash...OK                                                                                                            
Flashing firmware...OK                                                                                                            

Process finished with exit code 0.
```

**Review by josesimoes — APPROVED** [review]
Looks perfect now! Thanks for the final touch. 👍🏻

**Pull request merged**
