### PR TITLE
Refactor preview flag to be more clear

### PR DESCRIPTION
**Pull request by networkfusion**
## Motivation and Context
* Make the use of `preview` flag more clear for its intention.
* Remove NETDUINO3_WIFI example as it is a deprecated target.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:
- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
The plan for our new release policy was to keep using preview releases for major changes and experimental features. Because of this, we shouldn't be removing the preview option from nanoff! After all it's the most convenient way that we have to offer to devs to update they devices. Tried and tested.

**Comment by networkfusion** [comment]
> The plan for our new release policy was to keep using preview releases for major changes and experimental features. Because of this, we shouldn't be removing the preview option from nanoff! After all it's the most convenient way that we have to offer to devs to update they devices. Tried and tested.

Ok, that makes it a little different then... We should make that Very clear in the documentation... I will refactor to accomodate.

**Comment by josesimoes** [comment]
We don't need to "panic" about preview! 😅  it's just another option...
There are already mechanisms in the code to output a warning if a package older than 2 months is about to be used. 

There is no special warning when you add --preview to nuget or the like... That's just an option...

**Comment by networkfusion** [comment]
> We don't need to "panic" about preview! 😅 it's just another option... There are already mechanisms in the code to output a warning if a package older than 2 months is about to be used.
> 
> There is no special warning when you add --preview to nuget or the like... That's just an option...

I have made the intention of the `preview` flag more clear (except in the CN readme).  i.e. this PR makes it clear that the average user should not be using the preview flag. But they can use help, or read the readme properly to discover the option flag.

**Pull request merged**
