### PR TITLE
Fix allowing spaces in username folder path

### PR DESCRIPTION
**Pull request by KhyberPass**
When using nanoff (v1.20.0-preview.8) for a STM32 development board (in my case a STM32F429I-DISCOVERY) the firmware update fails. 

This is because the command line argument for the utility ST-LINK_CLI.exe that contains the path to the file to be programmed has a space in it and it is not quoted. The firmware files are automatically downloaded by nanoff and put in a directory under the users folder. In this case the Windows 10 username has a space in it and therefore the full path name to the firmware file has a space in it. 

The fix is to quote the path/filename for the argument to ST-LINK_CLI.exe

Also fixed a variable name typo at the same time.

## Description
There are 2 calls to ST-LINK_CLI.exe that use the full path/filename to the firmware files that are automatically downloaded. One for hex files and the other for binary files.

Add quotes around the path/filename argument for these calls.

Also fixed a typo cliOuput to cliOutput 

## Motivation and Context
Fixes nanoff firmware update when Windows 10 username has a space in it.

An issue was not created since this change is trivial.

## How Has This Been Tested?
Tested firmware update when a Windows 10 username has a space in it.
Windows 10 Pro, Version 20H2, OS build 19042.1052

Did not test on any other platforms.
Change isolated to STM targets, does not effect ESP or TI.

## Types of changes
- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nanoFirmwareFlasher?pullRequest=55) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nanoFirmwareFlasher?pullRequest=55) before we can accept your contribution.<br/><br/>:x: KhyberPass [sign now](https://cla.dotnetfoundation.org/nanoframework/nanoFirmwareFlasher?pullRequest=55)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nanoFirmwareFlasher?pullRequest=55) it.</sub>

**Review by josesimoes — APPROVED** [review]
Nice catch! Thank you for fixing it. 👍🙂

**Comment by josesimoes** [comment]
@KhyberPass can you please take a look at build error [here](https://dev.azure.com/nanoframework/nanoFirmwareFlasher/_build/results?buildId=20073&view=logs&jobId=845aa72f-45f3-593c-57df-c9fe6cf6fab5&j=845aa72f-45f3-593c-57df-c9fe6cf6fab5&t=acad4cb5-5976-5d4b-5fdc-1bcaa71ee9a5) and fix it? Thanks.

**Comment by KhyberPass** [comment]
Hi @josesimoes 
Yes I saw that error and had a look into it when I did the PR.
The file that it is failing on is "Esp32Firmware.cs(43,44): error CS1026: ) expected" when it does the build NuGet package.
I did not change this file, I only changed StmJtagDevice.cs so I figured it was something wrong with the auto build system.

I am not too sure why it is doing a NuGet build for nanoff anyway, is it a NuGet package?
When it was run back on 7 Jun it passed ok.
I will take a look and see if I can find anything.
Is there a way to re-run the checks?

**Comment by josesimoes** [comment]
> The file that it is failing on is "Esp32Firmware.cs(43,44): error CS1026: ) expected" when it does the build NuGet package.
> I did not change this file, I only changed StmJtagDevice.cs so I figured it was something wrong with the auto build system.

From the error it seems that's something is missing with other build flavours.

 
> I am not too sure why it is doing a NuGet build for nanoff anyway, is it a NuGet package?
A dotnet tool is distributed over nuget.org so these are pretty similar. Anyways, this also generates a regular NuGet package too.

> When it was run back on 7 Jun it passed ok.
> I will take a look and see if I can find anything.
> Is there a way to re-run the checks?

Yes, I've just re-run it.

**Comment by KhyberPass** [comment]
Looked into this and I have a path forward.

The problem was actually created by a commit PR #52. A change was done as part of this work that actually broke the build check. But this did not get blocked because at that time something went wrong with the build check and it was unable to complete. So rather than producing an error it produced a warning.

The problem is caused by a new line in Esp32Firmware.cs
	if (_partitionTableSize is not null)

The ‘is not’ keyword was introduced in C# version 9.0. The build check uses .Net Core 3.1.101 which uses C# version 8.0. Refer to [here ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) for the version matrix. 

The build worked ok for me because I am using VS2019 which is C# 9.0. When I force the project to C# 8.0 the build fails.

The changes pending in PR #54 are currently passing because this PR has changed the .Net version in azure-pipelines.yml from 3.1 to 5.0. 5.0 uses C# 9.0 so the build check works.

So this issues can be fixed 2 ways
1. Change the code to be C# 8.0 compatible. The advantage of this is that it will work with older versions of VS and .Net.
Change the line if (_partitionTableSize is not null) to if (_partitionTableSize != null)

2. Change the build check to use a newer version of .Net, 5.0 by updating file azure-pipelines.yml

Note: if option 1 is chosen then PR #54 can pick this up and change azure-pipelines.yml back.

@josesimoes  please let me know which way you want to go? Not too sure of your policies here.

I can fix the issue but did you want me to create a separate PR or issue for this or shall I do it as part of this PR?

**Comment by josesimoes** [comment]
@KhyberPass thanks for the thorough review and fix proposal!! 💯 

At this point in time it's probably safe to go with the move to .NET 5.0, so I would suggest that we merge #54.
After that those changes are merge into your PR and it should be good. 

Do you agree?

**Comment by KhyberPass** [comment]
Sounds good.
The same problem might be happening with nanoff and ESP32 so I will check that our over the weekend.

**Comment by josesimoes** [comment]
OK! 

1) #54 merged
2) merged develop in this PR
3) waiting for the build... 🤞🏻 😅

**Comment by KhyberPass** [comment]
I checked ESP32 and it is already ok. The path/file names are already quoted. So all is ready to go.

**Pull request merged**
